name: Build and release halsey-bot

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and build app
        run: npm run build

      - name: Start app
        if: success()
        run: npm run start

      - name: Verify config.json
        if: success()
        run: test -f config.json

      - name: Create zip
        if: success()
        run: npm run zip

      - name: Get package version
        if: success()
        run: echo ::set-env name=PACKAGE_VERSION::$(npm run -s show-version)

      - name: Create release
        if: success()
        uses: actions/create-release@v1
        with:
          tag_name: v${{ env.PACKAGE_VERSION }}
          release_name: Release v${{ env.PACKAGE_VERSION }}
          draft: true
          prerelease: false
          files: |
            halsey-bot.zip
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: halsey-bot.zip
          path: halsey-bot.zip
