name: Build and release halsey-bot

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies and build app
        run: npm run build

      - name: Start app
        if: success()
        run: npm run start

      - name: Verify it created config.json
        if: success()
        run: test -f config.json

      - name: Get package version
        if: success()
        run: echo "PACKAGE_VERSION=$(npm run -s show-version)" >> $GITHUB_ENV

      - name: Draft release
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Source ${{ env.PACKAGE_VERSION }}
          tag_name: ${{ env.PACKAGE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.PACKAGE_VERSION }}
